### ISSUE TITLE
WP-Katex not working: "Katex not defined"

### ISSUE THREAD

**Issue by delip** [as-com/wp-katex#10]
Hi, I'm seeing "katex not defined" message everywhere on my blog for a few days, where it used to render properly before. I thought it was my problem, but turns out andrewsun.com is having the same problem too. Inserting a screenshot here:

![screen shot 2016-10-30 at 2 10 33 pm](https://cloud.githubusercontent.com/assets/347398/19840044/dbf7b09a-9eaa-11e6-830e-880fcf41ed61.png)

**Comment by as-com** [comment]
Hmm, I cannot reproduce this issue. What is your browser and its version?

Also, try clearing your cache.
