### ISSUE TITLE
\displaystyle command lets the equation in math mode

### ISSUE THREAD

**Issue by i3vi3** [as-com/wp-katex#11]
If we write a command like

`
[latex]\displaystyle \sum_{i=1}^n[/latex]
`

I think it should displayed in inline mode but the rendering itself is like display mode
(e.g. with "i=1" just below \sum.)
In fact, this is the usage of \displaystyle and the original KaTeX also behaves like this.

The current \displaystyle in wp-katex seems to be equivalent to adding display="true to [latex],
but this is not a standard behavior.

I love this plug-in so much and would be very glad if you could fix this issue.

**Comment by as-com** [comment]
This is intended behavior, but you can work around this by putting a space before the `\displaystyle` at the beginning of the equation. For example:
```
[latex] \displaystyle whatever[/latex]
```

**Comment by i3vi3** [comment]
Thank you very much for your comment. It works as I intended :)
