### ISSUE TITLE
How come I can't insert Latex into a tooltip ?

### ISSUE THREAD

**Issue by reslus** [as-com/wp-katex#20]
Having an issue with this: 

[latex]{ q }_{ i }\quad ={ \quad q }_{ 1 }\quad ={ \quad q }_{ 2 }={ \quad q }_{ 3 }\quad =\quad \cdots \quad =\quad { q }_{ N }[/latex] 

inside of 

[su_tooltip style="yellow" position="top" title="definition" content="that means they're all the same!"]homogenous[/su_tooltip] 

Whenever I put it into the content tag, I get a bug. Do I need to be escaping things?

**Comment by reslus** [comment]
Even with curly brackets it doesn't work

**Comment by as-com** [comment]
This sounds like an issue with the Shortcodes Ultimate plugin not supporting shortcodes inside shortcode attributes. It appears they have [documentation](https://docs.getshortcodes.com/article/34-nested-shortcodes) on this subject, and if it still doesn't work, I would file an issue with them.
