### ISSUE TITLE
\mathcal parsing error

### ISSUE THREAD

**Issue by delip** [as-com/wp-katex#4]
I use \mathcal often in my notation like: 
[latex]L \in \mathcal{R}^{m\times d_1}[/latex]

This leads to a parsing error:
ParseError: KaTeX parse error: Expected 'EOF', got '\mathcal' at position 14: L \in \mathcal̲{R}^{m\times d 

Is it possible to support this?

**Comment by as-com** [comment]
The KaTeX people are working on it: https://github.com/Khan/KaTeX/issues/19

Try bugging them about it.

**Comment by delip** [comment]
Done! :)

**Comment by as-com** [comment]
Fixed in version 1.5.1.
