### ISSUE TITLE
Bizzare error rendering a particular equation

### ISSUE THREAD

**Issue by delip** [as-com/wp-katex#8]
For this equation:

```
[latex display="true"] \mathcal{L}_0 = \frac{1}{2}f(x_{ij})(w_i^\intercal \tilde{w}_j - \mathbf{pmi}(i, j))^2 [/latex]
```

I get the following error:

```
ParseError: KaTeX parse error: Unexpected character: '–' at position 64: al \tilde{w}_j ̲– \mathbf{pmi}
```

However, in the same equation if I flip the minus (-) to a plus (+), as in:

```
[latex display="true"] \mathcal{L}_0 = \frac{1}{2}f(x_{ij})(w_i^\intercal \tilde{w}_j + \mathbf{pmi}(i, j))^2 [/latex]
```

the equation parses and renders correctly. Isn't that strange? What could be going on here?

**Comment by as-com** [comment]
Eww, it's WordPress's texturizer changing it to an em-dash. I'm going to attempt a fix now.

**Comment by as-com** [comment]
I pushed a fix to the WordPress plugin repo. You should be able to find the update on your dashboard in a few moments. :smile:
